# Generated by Django 5.2 on 2025-05-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
